### ISSUE TITLE
Doesn't show any images

### ISSUE THREAD

**Issue by Ketchup901** [FlorentUguet/QBooru#6]
When I search (on any site), it gets stuck at "Loading thumbnails" at 35 %.

I can't click on anything.

Using Windows with latest release (1.12.1).

**Comment by JacqylFrost** [comment]
Same for me, but only on Gelbooru.

**Comment by FuSoftware** [comment]
Gelbooru restricted the API to registered users. Since I don't want to put my password hash into the program, I'm waiting that they release a proper API key system to make changes.

Until then, Gelbooru support is dropped. I'll start to work on a way to save Username + PWD hash into the config file for Gelbooru, but I wanted to finally drop cUrl support and change to QNetwork so that the program builds a single executable.

Just look through this topic : http://gelbooru.com/index.php?page=forum&s=view&id=3264

Some API abuse happened and they disabled direct image linking without the "http://gelbooru.com/" referer and restricted the API to USER+PWD-HASH logged users

Other sites are working fine. the program shouldn't be blocked since all the network operations are threaded (just not the config downloads when starting the program)

**Comment by FuSoftware** [comment]
Fixed in the 1.14 version. I still need to generalize the login process, but for now, Gelbooru is working.
